# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 2

final_space: true
# pwd: osc99
# terminal_background: ""
# accent_color: ""
shell_integration: true
# disable_cursor_positioning: false
patch_pwsh_bleed: true

# var:
#   ExecutionTime: init

transient_prompt:
  # filler: ""
  # filler: "─"
  foreground: darkGray
  template: "\n {{ .Segments.Status.String }}{{ if eq .Code 0 }} {{ else }} {{ reason .Code }}{{end}} </> {{ .Segments.ExecutionTime.FormattedMs }}\n\n<black,lightYellow>  {{ now | date \"15:04:05\" }} </><lightYellow></> "

# type: status code

blocks:
  - type: prompt # First block includes pre-main segments
    newline: true
    alignment: left
    filler: ""
    # overflow: ""

    segments:
      # Status code, execution time before main segments
      - type: status
        alias: Status
        style: plain
        # foreground: blue
        template: " {{ .String }}{{ if eq .Code 0 }} {{ else }} {{ reason .Code }}{{end}} </>"
        status_separator: " | "
        # templates_logic: first_match
        # templates:
        #   - " {{ if eq .Code 0 }}{{ .String }} {{ end }}</>"
        #   - " {{ .String }} {{ reason .Code }} </>"
        properties:
          always_enabled: true
          status_template: "{{ if eq .Code 0 }}<green>{{ else }}<red>{{ end }}"
          # status_template: "oh hey"
        # foreground_templates:
        #   - "{{ if eq .Code 0 }}green{{ end }}"
        #   - red

      - type: executiontime
        alias: ExecutionTime
        style: plain
        foreground: darkGray
        template: " {{ .FormattedMs }}\n\n"
        properties:
          always_enabled: true
          threshold: 500
          style: austin

      # Main segments start
      - type: os
        style: plain
        foreground: black
        background: lightYellow
        template: " {{ .Icon }}"
        properties:
          display_distro_name: false
          macos: " "
          linux: " "
          windows: " "
          alpine: " "
          aosc: " "
          arch: " "
          centos: " "
          coreos: " "
          debian: " "
          devuan: " "
          raspbian: " "
          elementary: " "
          fedora: " "
          gentoo: " "
          mageia: " "
          manjaro: " "
          mint: " "
          nixos: " "
          opensuse: " "
          redhat: " "
          sabayon: " "
          slackware: " "
          ubuntu: " "
          rocky: " "
          alma: " "
          android: " "

      - type: shell
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        foreground: black
        background: lightYellow
        template: '{{ if (eq .Name "pwsh")}} {{ else if (eq .Name "bash") }} {{ else if (eq .Name "zsh") }}󰬡 {{ else }}.Name{{ end }}'

      - type: session
        style: powerline
        powerline_symbol: 
        foreground: white
        background: darkGray
        template: "{{ if .SSHSession }} \U000F06F3 {{ end }}  {{ .HostName }}  {{ .UserName }}{{ if .Root }} {{ end }} "

      - type: git
        alias: Git
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        background: blue
        foreground: black
        template: " {{ url (cat .UpstreamIcon (base .UpstreamURL)) .UpstreamURL }} {{ .HEAD }}"
        # template: ' {{ url (cat .UpstreamIcon (base .UpstreamURL)) .UpstreamURL }}/{{ $dirs := split ".git" .Dir }}{{ $git_worktree := replace "worktrees" "" $dirs._1 | trimAll "/"  }}{{ $git_worktree }} '
        # {{ $git_main_abs_path := trimAll "/" $dirs._0 }}
        properties:
          fetch_status: false
          fetch_stash_count: false
          fetch_worktree_count: false
          fetch_upstream_icon: true
          fetch_bare_info: false
          fetch_user: false
          branch_max_length: 0
          branch_icon: " "
          branch_identical_icon: "≡ "
          branch_ahead_icon: "↑ "
          branch_behind_icon: "↓ "
          branch_gone_icon: "≢ "
          commit_icon: " "
          tag_icon: " "
          rebase_icon: " "
          cherry_pick_icon: " "
          revert_icon: " "
          merge_icon: " "
          no_commits_icon: " "
          github_icon: " "
          gitlab_icon: " "
          bitbucket_icon: " "
          azure_devops_icon: " "
          codecommit_icon: " "
          git_icon: " "

      - type: path
        alias: Path
        style: diamond
        leading_diamond: ""
        trailing_diamond: 
        background: blue
        foreground: black
        template: ' {{ if .Segments.Contains "Git" }}/{{ splitList (splitList "/" (replace "\\" "/" .Segments.Git.Dir) | last ) .Path | last | trimPrefix "/" }}{{ else }}{{ .Path }}{{end}} '
        properties:
          style: powerlevel
          folder_separator_icon: /
          # folder_separator_template:
          home_icon: "~"
          folder_icon: " "
          windows_registry_icon: 
          # max_depth: 3
          max_width: 50
          mapped_locations_enabled: true
          # mixed_threshold: 4
          hide_root_location: false
          cycle_folder_separator: false
          # folder_format: "<r>%s</r>"
          # gitdir_format: "</r>%s"

  - type: prompt # Second block on right side shows current status
    newline: false
    alignment: right
    filler: "<darkGray,transparent>─</>"
    segments:
      - type: upgrade
        style: diamond
        leading_diamond: 
        trailing_diamond: ""
        foreground: black
        background: lightGreen
        template: "  "

      - type: sysinfo
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        background: darkGray
        foreground: white
        template: "  {{ round .PhysicalPercentUsed .Precision }}% "
        properties:
          precision: 2

      - type: battery
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        background: lightRed
        foreground: black

      - type: time
        style: diamond
        leading_diamond: ""
        trailing_diamond: ""
        background: lightYellow
        foreground: black
        template: "  {{ .CurrentDate | date .Format }} "
        properties:
          time_format: "15:04:05"

  - type: prompt # Prompt block
    newline: true
    alignment: left
    segments:
      - type: text
        style: plain
        template: "{{ .Segments.Status.String }}❯</>"
        interactive: false
        # foreground: green
        # foreground_templates:
        #   - "{{ if .Code }}red{{ end }}"

tooltips:
  - type: go
    style: plain
    foreground: darkGray
    # template: "{{ .Segments.Git.Name }}({{ .Segments.Git.Email }})"
    template: " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    tips:
      - "go"

  - type: node
    style: plain
    foreground: darkGray
    template: " {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    tips:
      - "node"
      - "nvm"

  - type: npm
    style: plain
    foreground: darkGray
    template: " { if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }} "
    tips:
      - "npm"

  - type: kubectl
    style: plain
    foreground: darkGray
    template: "󱃾 {{ .Context }}{{ if .Namespace }} :: {{ .Namespace }}{{ end }} "
    tips:
      - "kubectl"

  - type: git
    tips:
      - "git"
    style: plain
    foreground: darkGray
    # template: ""
    templates_logic: join
    templates:
      - "{{ if .Working.Changed }} {{ .Working.String }}{{ end }} "
      - "{{ if gt .StashCount 0 }} {{ .StashCount }}{{ end }} "
      - "{{ if .Staging.Changed }} {{ .Staging.String }}{{ end }} "
      - "{{ if gt .Behind 0 }}\uf048 {{ .Behind }}{{ end }} "
      - "{{ if gt .Ahead 0 }}\uf051 {{ .Ahead }}{{ end }} "
    properties:
      fetch_status: true
      fetch_stash_count: true
      fetch_worktree_count: false
      fetch_upstream_icon: false
      fetch_bare_info: false
      fetch_user: false
      branch_max_length: 0
      branch_icon: " "
      branch_identical_icon: "≡ "
      branch_ahead_icon: "↑ "
      branch_behind_icon: "↓ "
      branch_gone_icon: "≢ "
      commit_icon: " "
      tag_icon: " "
      rebase_icon: " "
      cherry_pick_icon: " "
      revert_icon: " "
      merge_icon: " "
      no_commits_icon: " "
      github_icon: " "
      gitlab_icon: " "
      bitbucket_icon: " "
      azure_devops_icon: " "
      codecommit_icon: " "
      git_icon: " "

secondary_prompt:
  foreground: blue
  template: "  "
