linters:
  # disable-all: false
  # enable-all: false

  # fast: true

  presets:
    - bugs
    - comment
    # - complexity
    - error
    - format
    # - import
    # - metalinter
    # - module
    - performance
    # - sql
    - style
    # - test
    - unused

  enable:
    # default
    - errcheck
    - gosimple
    - govet
    - staticcheck
    - unused

    # additional
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - canonicalheader
    # - containedctx
    # - contextcheck
    # - copyloopvar
    # - cyclop
    # - decorder
    # - depguard
    # - dogsled
    # - dupl
    # - dupword
    # - durationcheck
    # - err113
    # - errchkjson
    # - errname
    # - errorlint
    # - execinquery
    # - exhaustive
    # - exhaustruct
    # - exportloopref
    # - exptostd
    # - fatcontext
    # - forbidigo
    # - forcetypeassert
    # - funlen
    # - gci
    # - ginkgolinter
    # - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gochecksumtype
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    # - godot
    # - godox
    # - gofmt
    # - gofumpt
    # - goheader
    # - goimports
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosmopolitan
    # - grouper
    # - iface
    # - importas
    # - inamedparam
    # - interfacebloat
    # - intrange
    # - ireturn
    # - lll
    # - loggercheck
    # - maintidx
    # - makezero
    # - mirror
    # - misspell
    # - mnd
    # - musttag
    # - nakedret
    # - nestif
    # - nilerr
    # - nilnesserr
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    # - perfsprint
    # - prealloc
    # - predeclared
    # - promlinter
    # - protogetter
    # - reassign
    # - recvcheck
    # - revive
    # - rowserrcheck
    # - sloglint
    # - spancheck
    # - sqlclosecheck
    # - stylecheck
    # - tagalign
    # - tagliatelle
    # - tenv
    # - testableexamples
    # - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - usestdlibvars
    # - usetesting
    # - varnamelen
    # - wastedassign
    # - whitespace
    # - wrapcheck
    # - wsl
    # - zerologlint

  disable:
    # - asasalint
    # - asciicheck
    # - bidichk
    # - bodyclose
    # - canonicalheader
    # - containedctx
    # - contextcheck
    # - copyloopvar
    # - cyclop
    # - decorder
    - depguard
    # - dogsled
    # - dupl
    # - dupword
    # - durationcheck
    # - err113
    # - errchkjson
    # - errname
    # - errorlint
    # - execinquery
    # - exhaustive
    # - exhaustruct
    # - exportloopref
    # - exptostd
    # - fatcontext
    # - forbidigo
    # - forcetypeassert
    # - funlen
    # - gci
    # - ginkgolinter
    # - gocheckcompilerdirectives
    # - gochecknoglobals
    # - gochecknoinits
    # - gochecksumtype
    # - gocognit
    # - goconst
    # - gocritic
    # - gocyclo
    - godot
    # - godox
    # - gofmt
    # - gofumpt
    # - goheader
    # - goimports
    # - gomoddirectives
    # - gomodguard
    # - goprintffuncname
    # - gosec
    # - gosmopolitan
    # - grouper
    # - iface
    # - importas
    # - inamedparam
    # - interfacebloat
    # - intrange
    # - ireturn
    - lll
    # - loggercheck
    # - maintidx
    # - makezero
    # - mirror
    # - misspell
    # - mnd
    # - musttag
    # - nakedret
    # - nestif
    # - nilerr
    # - nilnesserr
    # - nilnil
    # - nlreturn
    # - noctx
    # - nolintlint
    # - nonamedreturns
    # - nosprintfhostport
    # - paralleltest
    # - perfsprint
    # - prealloc
    # - predeclared
    # - promlinter
    # - protogetter
    # - reassign
    # - recvcheck
    # - revive
    # - rowserrcheck
    # - sloglint
    # - spancheck
    # - sqlclosecheck
    # - stylecheck
    # - tagalign
    # - tagliatelle
    # - tenv
    # - testableexamples
    # - testifylint
    # - testpackage
    # - thelper
    # - tparallel
    # - unconvert
    # - unparam
    # - usestdlibvars
    # - usetesting
    # - varnamelen
    # - wastedassign
    # - whitespace
    # - wrapcheck
    # - wsl
    # - zerologlint
